### ISSUE TITLE
[Feature] 能否支持一个字的中文名

### ISSUE THREAD

**Issue by WitheredWinter** [0XPYEX0/CnUsername#1]
如题，能否支持一个字的中文名。一个字的中文名目前在加入服务器时还是会报`Internal Exception: java.lang.IllegalStateException: Invalid characters in username`错误。

**Comment by 0XPYEX0** [comment]
不建议这种做法 单个字重复率太高了
你可以自己修改允许进入服务器的正则ID，自行构建
还是让玩家取两个字或者以上的名字吧 (叠词词恶心心)

**Comment by 0XPYEX0** [comment]
还是先开着吧
回头可能会推出配置文件 可以修改进服的正则 (画饼

**Comment by WitheredWinter** [comment]
大饼，好吃
yummy yummy

**Comment by 0XPYEX0** [comment]
具体方法看mcbbs帖子
