### ISSUE TITLE
[Bug] LuckPerms无法识别中文名

### ISSUE THREAD

**Issue by WitheredWinter** [0XPYEX0/CnUsername#2]
如题，Luckperms无法识别中文名，即使使用了javaagent进行命令修复。对中文名玩家进行权限修改会报错。
![image](https://github.com/0XPYEX0/CnUsername/assets/123742753/4c91f1ed-06c2-495f-8254-725cd7fdd0bc)

**Comment by 0XPYEX0** [comment]
![~$)H)9FL5PP{QF43UPF$1 Y](https://github.com/0XPYEX0/CnUsername/assets/50171612/8564ed5b-8178-4f9e-95c1-e3d6b42936c8)
请如图调整配置文件( plugins/LuckPerms/config.yml )
![image](https://github.com/0XPYEX0/CnUsername/assets/50171612/67306c6e-657b-4358-919a-950f1d376be5)

**Comment by WitheredWinter** [comment]
方法可行，感谢
之前忘反馈了，抱歉
