### ISSUE TITLE
[Feature] 插件的所有配置文件能不能都放在plugins中的文件夹

### ISSUE THREAD

**Issue by STBD1574** [0XPYEX0/CnUsername#4]
服务端文件夹多出一个CnUsername就很难受qwq

**Comment by 0XPYEX0** [comment]
这是为了统一两种加载方式而设计的
从javaagent方式加载的话，不好拿到插件文件夹

**Comment by 0XPYEX0** [comment]
其实CnUsername主要是以JavaAgent方式来处理的
插件模式加载，只是在拓展JavaAgent方式
本来就应当在服务端根目录()

**Comment by STBD1574** [comment]
eaoqwq

**Comment by 0XPYEX0** [comment]
不过你提醒我了
我下次要统一到根目录的文件夹里面

**Comment by 0XPYEX0** [comment]
Won't fix
