### ISSUE TITLE
[Bug] 无效正则导致无法进入服务器

### ISSUE THREAD

**Issue by Top4nk-777** [0XPYEX0/CnUsername#5]
paper服務端,我看到注意事項中有關閉perform-validate-username,但沒有找到這個選項
使用java -javaagent:/minecraft/CnUsername-1.0.9-all.jar=^([a-zA-Z0-9_]{3,16}|[a-zA-Z0-9_\u4e00-\u9fa5]{2,10})$ -jar /minecraft/server.jar啟動服務器,在日誌中能看到有被正常加載
中文id加入：Failed to verify username!

**Comment by Top4nk-777** [comment]
我的正則有問題,修復了

**Comment by 0XPYEX0** [comment]
看这个提示，你服务端是开了正版验证吧

CnUsername是提供给离线服务端的，因为Mojang本身并不允许除英文字母、下划线、数字以外的用户名，正版自然是没办法修改成中文名，也没办法进服

**Comment by 0XPYEX0** [comment]
> 我的正則有問題,修復了

正则有问题应该是提示Invalid Username🤔

**Comment by 0XPYEX0** [comment]
Invalid
